### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by yzt123** [vcheckzen/UnblockBilibili#1]
填上SESSDATA我的大会员就可以共享出去给别人用？

**Comment by vcheckzen** [comment]
> 填上SESSDATA我的大会员就可以共享出去给别人用？

没错，不过现在要填完整 Cookie，详见 README。

**Comment by yzt123** [comment]
> 
> 
> > 填上SESSDATA我的大会员就可以共享出去给别人用？
> 
> 没错，不过现在要填完整 Cookie，详见 README。

我比较希望的是这个脚本可以共享我的cookie，其他人直接安装脚本后就可以看番剧。但是我不知道共享cookie是否安全。
脚本网页有评论说VIP_SESSDATA需要跟别人借或者合租，我不怎么看番剧，不懂这是什么需求，难道是绕过账号登录实现账号共享效果？

**Comment by vcheckzen** [comment]
> > > 填上SESSDATA我的大会员就可以共享出去给别人用？
> > 
> > 
> > 没错，不过现在要填完整 Cookie，详见 README。
> 
> 我比较希望的是这个脚本可以共享我的cookie，其他人直接安装脚本后就可以看番剧。但是我不知道共享cookie是否安全。
> 脚本网页有评论说VIP_SESSDATA需要跟别人借或者合租，我不怎么看番剧，不懂这是什么需求，难道是绕过账号登录实现账号共享效果？

共享任何大会员的 cookie 都可以，包括你的。
共享后也确实是别人安装脚本就能看番。
共享 cookie 不安全。
cookie 跟登录等价，所以你说绕过登录也没错。
